name: Deploy to Test Back-end

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "2b6f91d1-f9b7-4201-94be-3ea636871827"
          heroku_app_name: "ancient-waters-32375" #Must be unique in Heroku
          heroku_email: "kenn.tnguyen@gmail.com"
