name: NodeJS CI Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: CI='' npm run build
        env:
          DB_URI: ${{secrets.DB_URI}}
          GMAIL_APP_PASSWORD_DEV: ${{secrets.GMAIL_APP_PASSWORD_DEV}}
          SERVICE: ${{secrets.SERVICE}}
          EMAIL: ${{secrets.EMAIL}}
          JWT_PUBLIC_KEY: ${{secrets.JWT_PUBLIC_KEY}}
          JWT_PRIVATE_KEY: ${{secrets.JWT_PRIVATE_KEY}}
          ALPHAVANTAGE_API_KEY: ${{secrets.ALPHAVANTAGE_API_KEY}}
          NEO4J_USERNAME: ${{secrets.NEO4J_USERNAME}}
          NEO4J_PASSWORD: ${{secrets.NEO4J_PASSWORD}}
          NEO4J_URI: ${{secrets.NEO4J_URI}}

      - name: Test
        run: npm run test-report
        env:
          TEST_DB_URI: ${{secrets.TEST_DB_URI}}
          GMAIL_APP_PASSWORD_DEV: ${{secrets.GMAIL_APP_PASSWORD_DEV}}
          SERVICE: ${{secrets.SERVICE}}
          EMAIL: ${{secrets.EMAIL}}
          JWT_PUBLIC_KEY: ${{secrets.JWT_PUBLIC_KEY}}
          JWT_PRIVATE_KEY: ${{secrets.JWT_PRIVATE_KEY}}
          ALPHAVANTAGE_API_KEY: ${{secrets.ALPHAVANTAGE_API_KEY}}
          NEO4J_USERNAME: ${{secrets.NEO4J_USERNAME}}
          NEO4J_PASSWORD: ${{secrets.NEO4J_PASSWORD}}
          NEO4J_URI: ${{secrets.NEO4J_URI}}

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
